-- Public baseline technique tags generated from docs/seeder.ts.
-- Keep this migration idempotent so local resets and production deploys converge.
insert into public.technique_tags (key, label, category, generated_by_account_id, is_public)
values
  ('armbar', 'Armbar', 'submission', null, true),
  ('straight-arm-lock', 'Straight Arm Lock', 'submission', null, true),
  ('choi-bar', 'Choi Bar', 'submission', null, true),
  ('juji-gatame', 'Juji Gatame', 'submission', null, true),
  ('rear-naked-choke', 'Rear Naked Choke', 'submission', null, true),
  ('cross-collar-choke', 'Cross Collar Choke', 'submission', null, true),
  ('bow-and-arrow-choke', 'Bow and Arrow Choke', 'submission', null, true),
  ('baseball-bat-choke', 'Baseball Bat Choke', 'submission', null, true),
  ('clock-choke', 'Clock Choke', 'submission', null, true),
  ('ezekiel-choke', 'Ezekiel Choke', 'submission', null, true),
  ('paper-cutter-choke', 'Paper Cutter Choke', 'submission', null, true),
  ('guillotine', 'Guillotine', 'submission', null, true),
  ('high-elbow-guillotine', 'High Elbow Guillotine', 'submission', null, true),
  ('arm-in-guillotine', 'Arm-In Guillotine', 'submission', null, true),
  ('anaconda-choke', 'Anaconda Choke', 'submission', null, true),
  ('darce-choke', 'D''Arce Choke', 'submission', null, true),
  ('peruvian-necktie', 'Peruvian Necktie', 'submission', null, true),
  ('north-south-choke', 'North South Choke', 'submission', null, true),
  ('triangle-choke', 'Triangle Choke', 'submission', null, true),
  ('arm-triangle', 'Arm Triangle', 'submission', null, true),
  ('kata-gatame', 'Kata Gatame', 'submission', null, true),
  ('loop-choke', 'Loop Choke', 'submission', null, true),
  ('short-choke', 'Short Choke', 'submission', null, true),
  ('kimura', 'Kimura', 'submission', null, true),
  ('americana', 'Americana', 'submission', null, true),
  ('mexicana', 'Mexicana', 'submission', null, true),
  ('omoplata', 'Omoplata', 'submission', null, true),
  ('monoplata', 'Monoplata', 'submission', null, true),
  ('tarikoplata', 'Tarikoplata', 'submission', null, true),
  ('wrist-lock', 'Wrist Lock', 'submission', null, true),
  ('straight-ankle-lock', 'Straight Ankle Lock', 'submission', null, true),
  ('toe-hold', 'Toe Hold', 'submission', null, true),
  ('kneebar', 'Kneebar', 'submission', null, true),
  ('inside-heel-hook', 'Inside Heel Hook', 'submission', null, true),
  ('outside-heel-hook', 'Outside Heel Hook', 'submission', null, true),
  ('calf-slicer', 'Calf Slicer', 'submission', null, true),
  ('bicep-slicer', 'Bicep Slicer', 'submission', null, true),
  ('clover-leaf', 'Clover Leaf', 'submission', null, true),
  ('estima-lock', 'Estima Lock', 'submission', null, true),
  ('aoki-lock', 'Aoki Lock', 'submission', null, true),
  ('banana-split', 'Banana Split', 'submission', null, true),
  ('electric-chair', 'Electric Chair', 'submission', null, true),
  ('mothers-milk', 'Mother''s Milk', 'submission', null, true),
  ('buggy-choke', 'Buggy Choke', 'submission', null, true),
  ('just-pressure', 'Just Pressure', 'submission', null, true),
  ('single-leg', 'Single Leg', 'takedown', null, true),
  ('high-crotch', 'High Crotch', 'takedown', null, true),
  ('double-leg', 'Double Leg', 'takedown', null, true),
  ('blast-double', 'Blast Double', 'takedown', null, true),
  ('low-single', 'Low Single', 'takedown', null, true),
  ('ankle-pick', 'Ankle Pick', 'takedown', null, true),
  ('knee-pick', 'Knee Pick', 'takedown', null, true),
  ('duck-under', 'Duck Under', 'takedown', null, true),
  ('arm-drag', 'Arm Drag', 'takedown', null, true),
  ('snap-down', 'Snap Down', 'takedown', null, true),
  ('front-headlock-go-behind', 'Front Headlock Go Behind', 'takedown', null, true),
  ('go-behind', 'Go Behind', 'takedown', null, true),
  ('body-lock-takedown', 'Body Lock Takedown', 'takedown', null, true),
  ('rear-body-lock', 'Rear Body Lock', 'takedown', null, true),
  ('inside-trip', 'Inside Trip', 'takedown', null, true),
  ('outside-trip', 'Outside Trip', 'takedown', null, true),
  ('knee-tap', 'Knee Tap', 'takedown', null, true),
  ('head-inside-single', 'Head Inside Single', 'takedown', null, true),
  ('head-outside-single', 'Head Outside Single', 'takedown', null, true),
  ('osoto-gari', 'Osoto Gari', 'takedown', null, true),
  ('osoto-otoshi', 'Osoto Otoshi', 'takedown', null, true),
  ('ouchi-gari', 'Ouchi Gari', 'takedown', null, true),
  ('kouchi-gari', 'Kouchi Gari', 'takedown', null, true),
  ('harai-goshi', 'Harai Goshi', 'takedown', null, true),
  ('uchi-mata', 'Uchi Mata', 'takedown', null, true),
  ('tai-otoshi', 'Tai Otoshi', 'takedown', null, true),
  ('seoi-nage', 'Seoi Nage', 'takedown', null, true),
  ('ippon-seoi-nage', 'Ippon Seoi Nage', 'takedown', null, true),
  ('morote-seoi-nage', 'Morote Seoi Nage', 'takedown', null, true),
  ('sasae-tsurikomi-ashi', 'Sasae Tsurikomi Ashi', 'takedown', null, true),
  ('de-ashi-barai', 'De Ashi Barai', 'takedown', null, true),
  ('okuri-ashi-barai', 'Okuri Ashi Barai', 'takedown', null, true),
  ('hiza-guruma', 'Hiza Guruma', 'takedown', null, true),
  ('tomoe-nage', 'Tomoe Nage', 'takedown', null, true),
  ('sumi-gaeshi', 'Sumi Gaeshi', 'takedown', null, true),
  ('yoko-tomoe-nage', 'Yoko Tomoe Nage', 'takedown', null, true),
  ('tani-otoshi', 'Tani Otoshi', 'takedown', null, true),
  ('yoko-wakare', 'Yoko Wakare', 'takedown', null, true),
  ('koshi-guruma', 'Koshi Guruma', 'takedown', null, true),
  ('collar-drag', 'Collar Drag', 'takedown', null, true),
  ('arm-drag-to-back', 'Arm Drag to Back', 'takedown', null, true),
  ('russian-tie', 'Russian Tie', 'takedown', null, true),
  ('slide-by', 'Slide By', 'takedown', null, true),
  ('2-on-1-takedown', '2-on-1 Takedown', 'takedown', null, true),
  ('underhook-to-knee-tap', 'Underhook to Knee Tap', 'takedown', null, true),
  ('seatbelt-drag', 'Seatbelt Drag', 'takedown', null, true),
  ('standing-body-lock', 'Standing Body Lock', 'takedown', null, true),
  ('standing-back-take', 'Standing Back Take', 'takedown', null, true),
  ('flying-triangle', 'Flying Triangle', 'takedown', null, true),
  ('flying-armbar', 'Flying Armbar', 'takedown', null, true),
  ('rolling-kimura', 'Rolling Kimura', 'takedown', null, true),
  ('front-headlock-roll', 'Front Headlock Roll', 'takedown', null, true),
  ('bear-hug', 'Bear Hug', 'takedown', null, true),
  ('lateral-drop', 'Lateral Drop', 'takedown', null, true),
  ('suplex', 'Suplex', 'takedown', null, true),
  ('arm-spin', 'Arm Spin', 'takedown', null, true),
  ('head-and-arm-throw', 'Head and Arm Throw', 'takedown', null, true),
  ('scissor-sweep', 'Scissor Sweep', 'sweep', null, true),
  ('flower-sweep', 'Flower Sweep', 'sweep', null, true),
  ('pendulum-sweep', 'Pendulum Sweep', 'sweep', null, true),
  ('hip-bump-sweep', 'Hip Bump Sweep', 'sweep', null, true),
  ('lumberjack-sweep', 'Lumberjack Sweep', 'sweep', null, true),
  ('waiter-sweep', 'Waiter Sweep', 'sweep', null, true),
  ('butterfly-sweep', 'Butterfly Sweep', 'sweep', null, true),
  ('elevator-sweep', 'Elevator Sweep', 'sweep', null, true),
  ('shoulder-crunch-sweep', 'Shoulder Crunch Sweep', 'sweep', null, true),
  ('arm-drag-sweep', 'Arm Drag Sweep', 'sweep', null, true),
  ('old-school-sweep', 'Old School Sweep', 'sweep', null, true),
  ('plan-b-sweep', 'Plan B Sweep', 'sweep', null, true),
  ('deep-half-sweep', 'Deep Half Sweep', 'sweep', null, true),
  ('dogfight-sweep', 'Dogfight Sweep', 'sweep', null, true),
  ('coyote-sweep', 'Coyote Sweep', 'sweep', null, true),
  ('john-wayne-sweep', 'John Wayne Sweep', 'sweep', null, true),
  ('de-la-riva-sweep', 'De La Riva Sweep', 'sweep', null, true),
  ('tripod-sweep', 'Tripod Sweep', 'sweep', null, true),
  ('sickle-sweep', 'Sickle Sweep', 'sweep', null, true),
  ('balloon-sweep', 'Balloon Sweep', 'sweep', null, true),
  ('technical-standup-sweep', 'Technical Standup Sweep', 'sweep', null, true),
  ('x-guard-sweep', 'X Guard Sweep', 'sweep', null, true),
  ('single-leg-x-sweep', 'Single Leg X Sweep', 'sweep', null, true),
  ('spider-sweep', 'Spider Sweep', 'sweep', null, true),
  ('lasso-sweep', 'Lasso Sweep', 'sweep', null, true),
  ('pendulum-lasso-sweep', 'Pendulum Lasso Sweep', 'sweep', null, true),
  ('hook-sweep', 'Hook Sweep', 'sweep', null, true),
  ('overhead-sweep', 'Overhead Sweep', 'sweep', null, true),
  ('dummy-sweep', 'Dummy Sweep', 'sweep', null, true),
  ('elbow-knee-escape', 'Elbow Knee Escape', 'escape', null, true),
  ('knee-elbow-escape', 'Knee Elbow Escape', 'escape', null, true),
  ('kipping-escape', 'Kipping Escape', 'escape', null, true),
  ('heel-drag-escape', 'Heel Drag Escape', 'escape', null, true),
  ('underhook-escape', 'Underhook Escape', 'escape', null, true),
  ('ghost-escape', 'Ghost Escape', 'escape', null, true),
  ('running-man-escape', 'Running Man Escape', 'escape', null, true),
  ('side-control-escape', 'Side Control Escape', 'escape', null, true),
  ('north-south-escape', 'North South Escape', 'escape', null, true),
  ('north-south-hip-escape', 'North South Hip Escape', 'escape', null, true),
  ('back-escape-two-on-one', 'Back Escape Two on One', 'escape', null, true),
  ('back-escape-shoulder-slide', 'Back Escape Shoulder Slide', 'escape', null, true),
  ('back-escape-to-half-guard', 'Back Escape to Half Guard', 'escape', null, true),
  ('back-escape-to-closed-guard', 'Back Escape to Closed Guard', 'escape', null, true),
  ('sit-out-escape', 'Sit Out Escape', 'escape', null, true),
  ('granby-escape', 'Granby Escape', 'escape', null, true),
  ('peek-out-escape', 'Peek Out Escape', 'escape', null, true),
  ('turtle-reguard', 'Turtle Reguard', 'escape', null, true),
  ('knee-on-belly-shrimp-escape', 'Knee on Belly Shrimp Escape', 'escape', null, true),
  ('knee-on-belly-leg-pummel', 'Knee on Belly Leg Pummel', 'escape', null, true),
  ('crucifix-escape', 'Crucifix Escape', 'escape', null, true),
  ('straight-ashi-escape', 'Straight Ashi Escape', 'escape', null, true),
  ('cross-ashi-escape', 'Cross Ashi Escape', 'escape', null, true),
  ('outside-ashi-escape', 'Outside Ashi Escape', 'escape', null, true),
  ('saddle-escape', 'Saddle Escape', 'escape', null, true),
  ('50-50-escape', '50/50 Escape', 'escape', null, true),
  ('shrimp-escape', 'Shrimp Escape', 'escape', null, true),
  ('bridge-and-shrimp', 'Bridge and Shrimp', 'escape', null, true),
  ('frame-and-reguard', 'Frame and Reguard', 'escape', null, true),
  ('leg-pummel-reguard', 'Leg Pummel Reguard', 'escape', null, true),
  ('upa', 'Upa', 'reversal', null, true),
  ('trap-and-roll', 'Trap and Roll', 'reversal', null, true),
  ('underhook-reversal', 'Underhook Reversal', 'reversal', null, true),
  ('ghost-escape-reversal', 'Ghost Escape Reversal', 'reversal', null, true),
  ('running-man-reversal', 'Running Man Reversal', 'reversal', null, true),
  ('north-south-rollover', 'North South Rollover', 'reversal', null, true),
  ('backdoor-reversal', 'Backdoor Reversal', 'reversal', null, true),
  ('bridge-and-roll', 'Bridge and Roll', 'reversal', null, true),
  ('wrestle-up-reversal', 'Wrestle Up Reversal', 'reversal', null, true),
  ('hip-heist-reversal', 'Hip Heist Reversal', 'reversal', null, true),
  ('arm-drag-back-take', 'Arm Drag Back Take', 'back-take', null, true),
  ('duck-under-back-take', 'Duck Under Back Take', 'back-take', null, true),
  ('berimbolo', 'Berimbolo', 'back-take', null, true),
  ('baby-bolo', 'Baby Bolo', 'back-take', null, true),
  ('kiss-of-the-dragon', 'Kiss of the Dragon', 'back-take', null, true),
  ('matrix', 'Matrix', 'back-take', null, true),
  ('crab-ride-back-take', 'Crab Ride Back Take', 'back-take', null, true),
  ('twister-hook-back-take', 'Twister Hook Back Take', 'back-take', null, true),
  ('truck-to-back', 'Truck to Back', 'back-take', null, true),
  ('dogfight-back-take', 'Dogfight Back Take', 'back-take', null, true),
  ('underhook-back-take', 'Underhook Back Take', 'back-take', null, true),
  ('waiter-back-take', 'Waiter Back Take', 'back-take', null, true),
  ('saddle-back-take', 'Saddle Back Take', 'back-take', null, true),
  ('cross-ashi-back-take', 'Cross Ashi Back Take', 'back-take', null, true),
  ('torreando-pass', 'Torreando Pass', 'guard-pass', null, true),
  ('leg-drag-pass', 'Leg Drag Pass', 'guard-pass', null, true),
  ('x-pass', 'X Pass', 'guard-pass', null, true),
  ('long-step-pass', 'Long Step Pass', 'guard-pass', null, true),
  ('side-smash-pass', 'Side Smash Pass', 'guard-pass', null, true),
  ('throw-by-pass', 'Throw By Pass', 'guard-pass', null, true),
  ('knee-slice-pass', 'Knee Slice Pass', 'guard-pass', null, true),
  ('knee-cut-pass', 'Knee Cut Pass', 'guard-pass', null, true),
  ('smash-pass', 'Smash Pass', 'guard-pass', null, true),
  ('over-under-pass', 'Over Under Pass', 'guard-pass', null, true),
  ('double-under-pass', 'Double Under Pass', 'guard-pass', null, true),
  ('stack-pass', 'Stack Pass', 'guard-pass', null, true),
  ('body-lock-pass', 'Body Lock Pass', 'guard-pass', null, true),
  ('half-guard-smash-pass', 'Half Guard Smash Pass', 'guard-pass', null, true),
  ('float-pass', 'Float Pass', 'guard-pass', null, true),
  ('backstep-pass', 'Backstep Pass', 'guard-pass', null, true),
  ('leg-pummel-pass', 'Leg Pummel Pass', 'guard-pass', null, true),
  ('cartwheel-pass', 'Cartwheel Pass', 'guard-pass', null, true),
  ('rolling-backtake-pass', 'Rolling Back Take Pass', 'guard-pass', null, true),
  ('weave-pass', 'Weave Pass', 'guard-pass', null, true),
  ('crossface-underhook-pass', 'Crossface Underhook Pass', 'guard-pass', null, true),
  ('flatten-and-pass', 'Flatten and Pass', 'guard-pass', null, true),
  ('headquarters-pass', 'Headquarters Pass', 'guard-pass', null, true),
  ('split-squat-pass', 'Split Squat Pass', 'guard-pass', null, true),
  ('shin-staple-pass', 'Shin Staple Pass', 'guard-pass', null, true),
  ('leg-weave-pass', 'Leg Weave Pass', 'guard-pass', null, true),
  ('shoulder-pin-pass', 'Shoulder Pin Pass', 'guard-pass', null, true),
  ('rugby-pass', 'Rugby Pass', 'guard-pass', null, true),
  ('camping', 'Camping', 'guard-pass', null, true),
  ('leg-pin-pass', 'Leg Pin Pass', 'guard-pass', null, true),
  ('single-leg-x-entry', 'Single Leg X Entry', 'leg-entry', null, true),
  ('straight-ashi-entry', 'Straight Ashi Entry', 'leg-entry', null, true),
  ('shin-to-shin-entry', 'Shin to Shin Entry', 'leg-entry', null, true),
  ('shin-to-single-leg-x', 'Shin to Single Leg X', 'leg-entry', null, true),
  ('x-guard-entry', 'X Guard Entry', 'leg-entry', null, true),
  ('reverse-x-entry', 'Reverse X Entry', 'leg-entry', null, true),
  ('saddle-entry', 'Saddle Entry', 'leg-entry', null, true),
  ('cross-ashi-entry', 'Cross Ashi Entry', 'leg-entry', null, true),
  ('inside-sankaku-entry', 'Inside Sankaku Entry', 'leg-entry', null, true),
  ('honey-hole-entry', 'Honey Hole Entry', 'leg-entry', null, true),
  ('outside-ashi-entry', 'Outside Ashi Entry', 'leg-entry', null, true),
  ('50-50-entry', '50/50 Entry', 'leg-entry', null, true),
  ('outside-50-50-entry', 'Outside 50/50 Entry', 'leg-entry', null, true),
  ('backside-50-50-entry', 'Backside 50/50 Entry', 'leg-entry', null, true),
  ('butterfly-leg-entry', 'Butterfly Leg Entry', 'leg-entry', null, true),
  ('elevation-leg-entry', 'Elevation Leg Entry', 'leg-entry', null, true),
  ('single-leg-to-ashi', 'Single Leg to Ashi', 'leg-entry', null, true),
  ('standing-leg-entry', 'Standing Leg Entry', 'leg-entry', null, true),
  ('false-reap-entry', 'False Reap Entry', 'leg-entry', null, true),
  ('cross-grip-leg-entry', 'Cross Grip Leg Entry', 'leg-entry', null, true),
  ('kani-basami-entry', 'Kani Basami Entry', 'leg-entry', null, true),
  ('leg-drag-leg-entry', 'Leg Drag Leg Entry', 'leg-entry', null, true),
  ('backstep-leg-entry', 'Backstep Leg Entry', 'leg-entry', null, true),
  ('off-balance', 'Off Balance', 'off-balance', null, true),
  ('kuzushi', 'Kuzushi', 'off-balance', null, true),
  ('mount', 'Mount', 'position', null, true),
  ('high-mount', 'High Mount', 'position', null, true),
  ('technical-mount', 'Technical Mount', 'position', null, true),
  ('s-mount', 'S-Mount', 'position', null, true),
  ('back-control', 'Back Control', 'position', null, true),
  ('body-triangle', 'Body Triangle', 'position', null, true),
  ('seatbelt-control', 'Seatbelt Control', 'position', null, true),
  ('side-control', 'Side Control', 'position', null, true),
  ('north-south', 'North South', 'position', null, true),
  ('knee-on-belly', 'Knee on Belly', 'position', null, true),
  ('scarf-hold', 'Scarf Hold', 'position', null, true),
  ('kesa-gatame', 'Kesa Gatame', 'position', null, true),
  ('reverse-kesa-gatame', 'Reverse Kesa Gatame', 'position', null, true),
  ('crucifix', 'Crucifix', 'position', null, true),
  ('turtle', 'Turtle', 'position', null, true),
  ('closed-guard', 'Closed Guard', 'position', null, true),
  ('open-guard', 'Open Guard', 'position', null, true),
  ('half-guard', 'Half Guard', 'position', null, true),
  ('deep-half-guard', 'Deep Half Guard', 'position', null, true),
  ('z-guard', 'Z Guard', 'position', null, true),
  ('knee-shield', 'Knee Shield', 'position', null, true),
  ('butterfly-guard', 'Butterfly Guard', 'position', null, true),
  ('seated-guard', 'Seated Guard', 'position', null, true),
  ('de-la-riva', 'De La Riva', 'position', null, true),
  ('reverse-de-la-riva', 'Reverse De La Riva', 'position', null, true),
  ('spider-guard', 'Spider Guard', 'position', null, true),
  ('lasso-guard', 'Lasso Guard', 'position', null, true),
  ('collar-sleeve-guard', 'Collar Sleeve Guard', 'position', null, true),
  ('single-leg-x', 'Single Leg X', 'position', null, true),
  ('x-guard', 'X Guard', 'position', null, true),
  ('reverse-x-guard', 'Reverse X Guard', 'position', null, true),
  ('k-guard', 'K Guard', 'position', null, true),
  ('50-50', '50/50', 'position', null, true),
  ('worm-guard', 'Worm Guard', 'position', null, true),
  ('lapel-guard', 'Lapel Guard', 'position', null, true),
  ('headquarters', 'Headquarters', 'position', null, true),
  ('combat-base', 'Combat Base', 'position', null, true),
  ('leg-drag-position', 'Leg Drag Position', 'position', null, true),
  ('smash-position', 'Smash Position', 'position', null, true),
  ('body-lock-position', 'Body Lock Position', 'position', null, true),
  ('top-half-guard', 'Top Half Guard', 'position', null, true),
  ('ashi-garami', 'Ashi Garami', 'position', null, true),
  ('straight-ashi', 'Straight Ashi', 'position', null, true),
  ('outside-ashi', 'Outside Ashi', 'position', null, true),
  ('cross-ashi', 'Cross Ashi', 'position', null, true),
  ('saddle', 'Saddle', 'position', null, true),
  ('inside-sankaku', 'Inside Sankaku', 'position', null, true),
  ('honey-hole', 'Honey Hole', 'position', null, true),
  ('dogfight', 'Dogfight', 'position', null, true),
  ('front-headlock', 'Front Headlock', 'position', null, true),
  ('truck', 'Truck', 'position', null, true),
  ('crab-ride', 'Crab Ride', 'position', null, true),
  ('single-leg-position', 'Single Leg Position', 'position', null, true),
  ('granby-roll', 'Granby Roll', 'guard-retention', null, true),
  ('invertion', 'Invertion', 'guard-retention', null, true),
  ('leg-pummel', 'Leg Pummel', 'guard-retention', null, true),
  ('shoulder-post', 'Shoulder Post', 'guard-retention', null, true),
  ('hip-heist', 'Hip Heist', 'guard-retention', null, true)
on conflict (key) do update
set
  label = excluded.label,
  category = excluded.category,
  generated_by_account_id = null,
  is_public = true,
  updated_date = now();
